#!/bin/bash
# MENU DE SELECTION POUR Spotnik-3.1
#
#  F5NLG  08/09/2020
#

while : ; do

choix=$(whiptail --title "Spotnik Menu 3.1"  --menu "                    >> Make your Choice: " 28 60 21 \
1 " Restart Spotnik on Stand Alone '95'" \
2 " Restart Spotnik on RRF '96'" \
3 " Restart Spotnik on FON Room '97'" \
4 " Restart Spotnik on TEC Room '98'" \
5 " Restart Spotnik on INT Room '99'" \
6 " Restart Spotnik on BAV Room '100'" \
7 " Restart Spotnik on LOC Room '101'" \
8 " Restart Spotnik on EXP Room '102'" \
9 " Restart Spotnik on EchoLink '103'" \
10 " Restart Spotnik on Regional '104'" \
11 " See Spotnik working (Logs) 'ctrl c'to leave" \
12 " Configure Wifi or network" \
13 " Trim Sound Alsamixer" \
14 " Edit Svxlink.cfg for all reflectors" \
15 " Edit Svxlink.el for EchoLink." \
16 " Edit ModuleEchoLink.conf" \
17 " Edit Airport for meteo" \
18 " MC Midnight Commander" \
19 " Configure mail account for Propagation Monitor" \
20 " Configure SA818 Radio Spotnik Delta only " \
21 " Configure Dwagent " 3>&1 1>&2 2>&3)

exitstatus=$?

#on recupere ce choix
#exitstatus=$?
if [ $exitstatus = 0 ]; then
    echo "Your chosen option:" $choix
else
    echo "You chose Cancel."; break;
fi



# case : action en fonction du choix

case $choix in

1)
/etc/spotnik/restart.default ;;

2)
/etc/spotnik/restart.rrf ;;

3)
/etc/spotnik/restart.fon ;;

4)
/etc/spotnik/restart.tec ;;

5)
/etc/spotnik/restart.int ;;

6)
/etc/spotnik/restart.bav ;;

7)
/etc/spotnik/restart.loc ;;

8)
/etc/spotnik/restart.exp ;;

9)
/etc/spotnik/restart.el ;;

10)
/etc/spotnik/restart.reg ;;

11)
/etc/spotnik/view_svx ;;

12)
nmtui ;;

13)
alsamixer && alsactl store ;;

14)
mcedit /etc/spotnik/svxlink.cfg ;;

15)
mcedit /etc/spotnik/svxlink.el ;;

16)
mcedit /etc/spotnik/svxlink.d/ModuleEchoLink.conf ;;

17)
mcedit /etc/spotnik/svxlink.d/ModuleMetarInfo.conf ;;

18)
mc /etc/spotnik ;;

19)
fetchsetup ;;

20)
818-prog ;;

21)
sh /usr/share/dwagent/native/configure ;;

esac

done
exit 0
